CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'havyilma'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'havyilma'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';